### ISSUE TITLE
bug to produce note

### ISSUE THREAD

**Issue by Steph77** [Microsoft/pxt-bluetooth-midi#1]
I've made some tests, there is a strange bug when I wanna send a midi BLE as an event (test of button A on the pic) it doesn't work but when i made a conditionnal test in a loop, it works (button B on the pic). I also get an error message (even if i only use one start bluetooth block, removing the  start block don't solve this bug)
![image](https://cloud.githubusercontent.com/assets/11035731/25292492/ac221590-26d6-11e7-8e00-6ae7382e6840.png)

**Comment by pelikhan** [comment]
This issue is fixed.
