### ISSUE TITLE
Bug when I let a button pressed to generate a note

### ISSUE THREAD

**Issue by Steph77** [Microsoft/pxt-bluetooth-midi#2]
Another bug, when i let the button B pushed, it make noise like i was tapping without stopping and garage band detect a problem and stop songs.
I had the same problem when i developped my arduino midi BLE piano. I solved the problem by using variables to memorize if key is pressed. 
to make it transparent for student, i made one function per note, this is a copy/paste of the code (i'm not a great programmer...)
[midi.txt](https://github.com/Microsoft/pxt-bluetooth-midi/files/948087/midi.txt)

**Comment by pelikhan** [comment]
Could you share the javascript of your project -- or copy the shared project url?

**Comment by Steph77** [comment]
https://pxt.microbit.org/_esLdJWCpxWUx

**Comment by Steph77** [comment]
I test it on garage band on an Ipad

**Comment by pelikhan** [comment]
See updated library.
