### ISSUE TITLE
How to get a note to play in GarageBand?

### ISSUE THREAD

**Issue by Bluebie** [Microsoft/pxt-bluetooth-midi#3]
I've tried a few times to use this, and while I can get it to connect to my iPhone 5s, sending notes doesn't seem to work. I pair the microbit via the microbit app, check it's connected in the iOS bluetooth settings, go in to garage band, in to it's advanced settings, connect to the microbit, and everything seems happy, the microbit indicates it has a device connected, but garageband never responds to any keypress events.

```typescript
basic.forever(() => {
    if (input.buttonIsPressed(Button.A)) {
        midi.toneOn(262)
        led.plot(0, 3)
    } else {
        midi.toneOff(262)
        led.unplot(0, 3)
    }
})
input.onGesture(Gesture.ThreeG, () => {
    midi.playDrum(DrumSound.LowBongo)
})
bluetooth.onBluetoothConnected(() => {
    led.plot(4, 3)
})
bluetooth.onBluetoothDisconnected(() => {
    led.unplot(4, 3)
})
basic.showLeds(`
    . . . . .
    . # . # .
    . . . . .
    . . . . .
    . # # # .
    `)
bluetooth.startMidiService()
```

LEDs on the microbit indicate connection works, and the button press works. I've tried before with event based button reading and that didn't work. I just can't figure it out. Maybe someone could make a video of this being used to explain how to use it in practice? all i found was one in japanese, connecting to a windows pc, but unfortunately my PC doesn't have BLE support, only my Mac, which doesn't seem to be able to connect to it as a bluetooth midi device at all.

**Comment by linclip** [comment]
I have chibi:bit which is a micro:bit compatible board. With this board, I could connect Bluetooth MIDI by the following video method.
https://www.youtube.com/watch?v=RA8Y_zW4jn0
I want to know if it works the same way with your micro:bit.

**Comment by Bluebie** [comment]
Ah yes! That works. I just needed to put the Start Bluetooth MIDI Service block inside the bluetooth connected event instead of the start event. How confusing! I would have thought the device would need to start advertising MIDI before it was connected to, to appear in garageband.
