### ISSUE TITLE
Can't find the "bluetooth start midi service" block

### ISSUE THREAD

**Issue by gunhaxxor** [Microsoft/pxt-bluetooth-midi#9]
I've watched an example video online ([https://www.youtube.com/watch?v=RA8Y_zW4jn0](https://www.youtube.com/watch?v=RA8Y_zW4jn0)) where they use a block from the bluetooth category to start the bluetooth midi service.

But it is nowhere to be found when adding the bluetooth-midi package to the makecode project. What is wrong?

**Comment by linclip** [comment]
In the current version, "bluetooth start midi service" block is unnecessary.
It will auto start. I checked it with v2.0.12.
By the way, the example video you showed is what I made in the past.

**Comment by gunhaxxor** [comment]
Ok.
I would advice for making the documentation a bit more thourough. 

For me I it worked when I deactivated pairing requirement in the project settings in the microbit block editor (makecode.microbit.org).

Things that are/were unclear to me:
How must the microbit be paired for the library to work? 
The midi library starts the ble-service automatically (why?). 
How do you send control change messages? The function block only seem to expect one parameter, while cc usually contains a cc "address" and a value.

**Comment by linclip** [comment]
The issue with Control Change is due to the "pxt-midi" package. 
So, I submitted the issue to "pxt-midi".

https://github.com/Microsoft/pxt-midi/issues/8#issue-372215126

**Comment by linclip** [comment]
control change block fixed.
